### ISSUE TITLE
[emails & messages] tRPC internal server error while saving configuration 

### ISSUE THREAD

**Issue by madmonkeyworks** [saleor/apps#1135]
Hi there, 

I am self-hosting the Emails & Messages Saleor app and testing it in Saleor dev sandbox. 
When saving email provider configuration, an internal server error pops up. 
This error appears only in Saleor dev sandbox. Local deployment on saleor-platform works well.

**Setup**
- Saleor dev sandbox 
- Emails & Messages app deployed on AWS Amplify
- Custom APL using AWS  graphql (dynamo DB)

**Steps to reproduce**
1. Self-host Emails & Messages app (in my case it's AWS Amplify)
2. Go to app configuration
3. Enter details for "SMTP server" > hit save [configuration successfully saved]
4. Enter details for "Sender" > hit save [saving configuration fails with error 500]

**Error**
```
"name": "tRPC error",
"err": {
        "type": "TRPCError",
        "message": "Internal server error",
        "stack": "TRPCError: Internal server error\n    at throwTrpcErrorFromConfigurationServiceError (/tmp/app/.next/server/pages/api/trpc/[trpc].js:918:11)\n    at /tmp/app/.next/server/pages/api/trpc/[trpc].js:1101:20\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async resolveMiddleware (file:///var/task/node_modules/@trpc/server/dist/index.mjs:420:30)\n    at async callRecursive (file:///var/task/node_modules/@trpc/server/dist/index.mjs:456:32)\n    at async callRecursive (file:///var/task/node_modules/@trpc/server/dist/index.mjs:456:32)\n    at async /tmp/app/.next/server/pages/api/trpc/[trpc].js:1230:20\n    at async callRecursive (file:///var/task/node_modules/@trpc/server/dist/index.mjs:456:32)\n    at async callRecursive (file:///var/task/node_modules/@trpc/server/dist/index.mjs:456:32)\n    at async callRecursive (file:///var/task/node_modules/@trpc/server/dist/index.mjs:456:32)",
        "code": "INTERNAL_SERVER_ERROR",
        "name": "TRPCError"
    },
"msg": "smtpConfiguration.updateSender returned error:"
```

As I mentioned, all works well in local development, i.e. saleor-platform + app via localhost, with both custom APL and file APL. It's only the Saleor dev sandbox and app deploy on AWS which trows the error. 

Can you help?

**Comment by lkostrowski** [comment]
Please set `APP_LOG_LEVEL=trace` and check if you have some logs in the console

**Comment by lkostrowski** [comment]
At the moment only I can help is that you check the error source (updateSender procedure) and try to log the error. Looks like its missing in the logs. I'd be great if you open the PR if you have the fix

**Comment by piotrgrundas** [comment]
@lkostrowski Same happens when using salor hosted app in cloud 😞 
![image](https://github.com/saleor/apps/assets/5078402/fe7c282a-4c04-4e10-aa1b-a8f762c7b53a)
