### ISSUE TITLE
QA: Emails & Messages App testing

### ISSUE THREAD

**Issue by krzysztofwolski** [saleor/apps#686]
# App installation:
- [ ] User must have `Manage Apps`, `Manage Users` and `Manage Orders` permissions to install the app
- [ ] After the app installation, the configuration panel should be accessible
- [ ] User should not be able to install the App in Saleor version < 3.11.7

# SMTP

To test if the emails are sent, I recommend using the https://mailtrap.io/ and fill SMTP details in the SMTP configuration.

All requirements below are mandatory for the event to be sent:
- Configuration has to be **active**
- API credentials has to be set up
- Sender has to be set up
- Event has to be configured
    - it has to be **active**
    - template must be set up

## Creating configuration

- [ ] User can add a new configuration, using `Add provider` button and choosing SMTP
- [ ] User can see configuration details, by clicking on `Edit` button on configurations list
- [ ] When user changes width of the browser window, the 2 column layout should change to single column

## Editing existing configuration
- [ ] User can modify `Status and name` section
- [ ] User can modify `Connect SMTP server` section
- [ ] User can modify `Sender` section
- [ ] User can remove the configuration

### `Events` section
- [ ] User should not be able to enable `Gift Card Sent` event, when installed App on Saleor version <3.13
- [ ] User should be able to activate events
- [ ] User can edit event email template

#### Template editing
- [ ] User should be able to use handlebars templates in the subject field (example `{{ order.id }}`) with the data in the example payload 
- [ ] User can see preview of the template changes, when editing the template
- [ ] User should be able to use handlebars templates in the subject field (example `{{ order.id }}`) with the data in the example payload 
- [ ] User can see preview of the subject changes, when editing the template

### `Channels` section
- [ ] When channel `overwrite` is not selected, configuration is used with all channels
- [ ] When using channel overwrite and `include` option, configuration is used only for channels specified on the list
- [ ] When using channel overwrite and `exclude` option, configuration is used for all channels beside specified on the list

# Sendgrid

To perform test, you will need:
- Sendgrid Account
- Sendgrid API key
- Configured Sender
- Created dynamic templates

All requirements below are mandatory for the event to be sent:
- Configuration has to be **active**
- API credentials has to be set up
- Sandbox mode has to be turned off
- Sender has to be chosen from existing ones
- Event has to be configured
    - it has to be **active**
    - template must be chosen

## Creating configuration

- [ ] User can add a new configuration, using `Add provider` button and choosing Sendgrid
- [ ] User can see configuration details, by clicking on `Edit` button on configurations list
- [ ] When user changes width of the browser window, the 2 column layout should change to single column

## Editing existing configuration
- [ ] User can modify `Status and name` section
- [ ] User can modify `API connection` section

- [ ] User can choose sender in the `Sender` section, from senders created in Sendgrid dashboard 

### `Events` section
- [ ] User should not be able to enable `Gift Card Sent` event, when installed App on Saleor version <3.13
- [ ] User should be able to activate events
- [ ] User can assign email template, from list of dynamic templates configured in Sendgrid dashboard

### `Channels` section
- [ ] When channel `overwrite` is not selected, configuration is used with all channels
- [ ] When using channel overwrite and `include` option, configuration is used only for channels specified on the list
- [ ] When using channel overwrite and `exclude` option, configuration is used for all channels beside specified on the list

# Installation manifest URLs

https://emails-and-messages.staging.saleor.app/api/manifest

**Comment by yellowee** [comment]
Checked SMTP config with mailtrap.io:

❌ 1. Console error on the app page:

```Uncaught (in promise) DOMException: Blocked a frame with origin "https://emails-and-messages.staging.saleor.app" from accessing a cross-origin frame.
    at https://vercel.live/_next-live/feedback/feedback.js:1:91
    at https://vercel.live/_next-live/feedback/feedback.js:1:51322```
    
![Screenshot 2023-06-29 at 15 02 01](https://github.com/saleor/apps/assets/24992893/38a37662-0e7d-4c86-b5c6-268a956da49a)

✅ Configuration CRUD

# Events:

❌ 2. I can enable ``Gift Card Sent`` event and edit its template, even though I am on the master staging 
```dashboard v3.14.0-dev || core v3.15.0-a.0```

![Screenshot 2023-06-29 at 13 41 33](https://github.com/saleor/apps/assets/24992893/c6f2fad5-99ce-40b8-b9d9-fda16bea5bef)

✅ Template editing

# Changing channel settings:

❓3. I think I shouldn't be allowed to choose channels in include/exclude section when ``Override channels`` checkbox is not selected. IMO it's bit confusing. The screenshot below shows the state **after** saving:

![1](https://github.com/saleor/apps/assets/24992893/b7df6a05-242c-4802-a0de-dddd14687269)

```curl 'https://emails-and-messages.staging.saleor.app/api/trpc/smtpConfiguration.getConfiguration?batch=1&input=%7B%220%22%3A%7B%22id%22%3A%2216880445288643d4mlf%22%7D%7D' \
  -H 'authority: emails-and-messages.staging.saleor.app' \
  -H 'accept: */*' \
  -H 'accept-language: en-GB,en;q=0.9' \
  -H 'authorization-bearer: eyJhbGciOiJSUzI1NiIsImtpZCI6IjEiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE2ODgwNDQzMTMsIm93bmVyIjoic2FsZW9yIiwiaXNzIjoiaHR0cHM6Ly9tYXN0ZXIuc3RhZ2luZy5zYWxlb3IuY2xvdWQvZ3JhcGhxbC8iLCJleHAiOjE2ODgxMzA3MTMsInRva2VuIjoiTTJpckZtelZBU1IzIiwiZW1haWwiOiJ0ZXN0ZXJzK2Rhc2hib2FyZEBzYWxlb3IuaW8iLCJ0eXBlIjoidGhpcmRwYXJ0eSIsInVzZXJfaWQiOiJWWE5sY2pveE1ETXoiLCJpc19zdGFmZiI6dHJ1ZSwiYXBwIjoiUVhCd09qZzAiLCJwZXJtaXNzaW9ucyI6WyJNQU5BR0VfVVNFUlMiLCJNQU5BR0VfT1JERVJTIl0sInVzZXJfcGVybWlzc2lvbnMiOlsiTUFOQUdFX0NIQU5ORUxTIiwiTUFOQUdFX1RBWEVTIiwiTUFOQUdFX09SREVSU19JTVBPUlQiLCJNQU5BR0VfTUVOVVMiLCJNQU5BR0VfVFJBTlNMQVRJT05TIiwiTUFOQUdFX09CU0VSVkFCSUxJVFkiLCJIQU5ETEVfVEFYRVMiLCJNQU5BR0VfUEFHRVMiLCJNQU5BR0VfUExVR0lOUyIsIkhBTkRMRV9DSEVDS09VVFMiLCJNQU5BR0VfT1JERVJTIiwiTUFOQUdFX1VTRVJTIiwiTUFOQUdFX1BST0RVQ1RTIiwiTUFOQUdFX0NIRUNLT1VUUyIsIkhBTkRMRV9QQVlNRU5UUyIsIk1BTkFHRV9QUk9EVUNUX1RZUEVTX0FORF9BVFRSSUJVVEVTIiwiTUFOQUdFX1NUQUZGIiwiTUFOQUdFX0dJRlRfQ0FSRCIsIk1BTkFHRV9TSElQUElORyIsIk1BTkFHRV9ESVNDT1VOVFMiLCJNQU5BR0VfQVBQUyIsIk1BTkFHRV9QQUdFX1RZUEVTX0FORF9BVFRSSUJVVEVTIiwiSU1QRVJTT05BVEVfVVNFUiIsIk1BTkFHRV9TRVRUSU5HUyJdfQ.OI8cFd0I3IHu6ftg5Uw35l9lyviaySf9IpalJWYxZQcKI3wXcsdbeHFtQNEr94H-1HppUBpgXgb7dWLq6epaQUJgbSnj5ouk5TdPnVXv68hyxgpcMNv199B811cDV5Mi-QqJLTZWymt4ktBeQyFMr4sDZDjjFxX6Bc7W8UFMyIL49bGB7HDXf8LJpo0MLocCVSJPsMMNGoSkCeH5H-6dIRT14emRzAetHoTs8jgZejrqjRZMyIYYfMxaxK3VmLH9aodDrpmLcgnKJNvgMiKfKggxOvfjvyNtxcc3dGwwjacnlnKs0D8r0rpC3DU22x0vQESOoY3R7U17Ovr3DEy4wA' \
  -H 'content-type: application/json' \
  -H 'referer: https://emails-and-messages.staging.saleor.app/configuration/smtp/16880445288643d4mlf' \
  -H 'saleor-api-url: https://master.staging.saleor.cloud/graphql/' \
  -H 'sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  --compressed```

I am not sure the request response should differ only in ``override`` flag on ``POST https://emails-and-messages.staging.saleor.app/api/trpc/smtpConfiguration.updateChannels?batch=1``

![resp](https://github.com/saleor/apps/assets/24992893/5de93a83-18be-402e-a6c4-36f841c1c64e)

**Comment by krzysztofwolski** [comment]
@yellowee 

> ❌ 2. I can enable ``Gift Card Sent`` event and edit its template, even though I am on the master staging 

Gift card sent is **disabled** for Saleor versions <3.13. Since core is at 3.15 it is enabled as intended :)

**Comment by yellowee** [comment]
Checked SendGrid config:

❌ 1. The same console error on the app page:

```Uncaught (in promise) DOMException: Blocked a frame with origin "https://emails-and-messages.staging.saleor.app" from accessing a cross-origin frame.
    at https://vercel.live/_next-live/feedback/feedback.js:1:91
    at https://vercel.live/_next-live/feedback/feedback.js:1:51322
```
✅ Configuration CRUD
✅ Fetching data from SendGrid acct.

❓ Events:
I can save an event even when no dynamic template is selected - not sure it is a bug or not.
![Screenshot 2023-07-03 at 10 55 36](https://github.com/saleor/apps/assets/24992893/2a6c8ebf-2c83-4807-b872-903cb4bd03d7)

❓ Channel settings - the same as in SMTP above

--------------------------------------------------------------------------------------------------------------

Please note: I do not see any emails sent to my Mailtrap nor SendGrid inboxes when configured events are triggered (eg. Order confirmation email is not received when I create an order for the applicable channel) and I would consider it a bug unless I do not have an appropriate config inside those services set - please advise

**Comment by krzysztofwolski** [comment]
@yellowee thanks!

- [ ] Disable enabling the event before template assignment
TODO. Agree, the app should not allow that. That's an incorrect setup.

- The same console error on the app page
Seems to be some error with vercel preview environments. Not blocking, I'll take a look later.

- [ ] Investigating the issue with missing deliveries
🛑  Critical. Investigating ATM.

**Comment by lkostrowski** [comment]
@krzysztofwolski can we close it and contiue with feature parity QA ?

**Comment by yellowee** [comment]
@krzysztofwolski Issues to be still addressed:

1. Some events trigger sending the same email twice (SMTP).
2. SMTP ports: not sure if all available ports (eg. in Mailtrap) should work for chosen config - as discussed on slack: only port 2525 works.
3. Unsure how to check Sendgrid email sending - I did not get any email when an event was triggered.
4. Vercel console error still appears on app configuration page.
5. Choosing channels in include/exclude section is still possible when Override channels checkbox is not selected.

Please refer to the comments above for more details, thanks!
